# Generated by Django 3.0.7 on 2020-06-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webaap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='More_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_name', models.CharField(max_length=10)),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
