# Generated by Django 3.0.7 on 2020-06-27 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webaap', '0002_more_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='upadte_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webaap.student')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webaap.More_Info')),
            ],
        ),
    ]
